### ISSUE TITLE
What is the License of this software?

### ISSUE THREAD

**Issue by orlcp440** [thounny/finance-tracker#1]
I would like to know the License used in this software to see if I can use it for free and make modifications and even create commercial software based on it. Is it an open source License? Which one?

**Comment by thounny** [comment]
> I would like to know the License used in this software to see if I can use it for free and make modifications and even create commercial software based on it. Is it an open source License? Which one?

Hi there, thank you for your interest in the finance tracker!

This software is free to use, and you are welcome to make modifications to it. You can also use it as part of a commercial project if needed. Feel free to explore and adapt it to your requirements!

Let me know if you have any other questions or need further clarification.
